name: LeviJethro
favicon: null
layout_spectrum: 0.50786
typography_spectrum: 0.50393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcfe'
    - '#5f514e'
    - '#c9ca84'
    - '#141727'
    - '#fc8149'
  brandStrength: 0.625
  lightness: 0.9375
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
