name: LeviJethro
favicon: null
layout_spectrum: 0.97096
typography_spectrum: 0.53383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#473939'
    - '#a3b6d4'
    - '#f0efed'
    - '#e3684d'
    - '#fb1051'
  brandStrength: 0.8719639128539711
  lightness: 0.5551910132635385
  saturation: 0.059221549425274134
  rhythmicContrast: 0.877811458427459
purpose: []
