name: LeviJethro
favicon: null
layout_spectrum: 0.97096
typography_spectrum: 0.53383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcfe'
    - '#5f514e'
    - '#c9ca84'
    - '#141727'
    - '#fc8149'
  brandStrength: 0.5
  lightness: 0.5551910132635385
  saturation: 0.059221549425274134
  rhythmicContrast: 0.5
purpose: []
